server:
  port: 8081

  tomcat:
    relaxed-query-chars: ['|','{','}','[',']']
    relaxed-path-chars: ['|','{','}','[',']']

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.174.238:3306/rxl-back-end-template?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: mysqlrxl
  redis:
    host: 101.132.174.238
    port: 6379
    database: 1
  main:
    allow-bean-definition-overriding: true    # 允许重复bean

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: delFlag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0